export const metadata = {
  title: "A for Ai signin",
  description: "Generated by create next app",
};

export default function SignInLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      hi
      {children}
    </div>
  );
}
