import { getServerSession, Session } from "next-auth";
import "./globals.css";
import { Inter } from "next/font/google";
import {GET, POST} from "./api/auth/[...nextauth]/route";
import { SessionProvider } from "next-auth/react";
import Login from "@/Components/Login";
import HomePage from "./page";
import SignUpPage from "./signup/page";
import Dashpage from "./dashboard/page";
import NextAuthProvider from "@/Components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AforAi",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session: Session| null = await getServerSession(GET);
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <NextAuthProvider session={session}>
        {/* <SessionProvider session={session}> */}
          {session ? <Dashpage /> : children}
        {/* </SessionProvider> */}

        </NextAuthProvider>
      </body>
    </html>
  );
}
